-- CREATE TABLE notifications (
-- 	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
-- 	user_id UUID NOT NULL,
-- 	message TEXT NOT NULL,
-- 	read BOOLEAN DEFAULT FALSE,
-- 	created_at TIMESTAMP DEFAULT NOW()
-- );